[tool.poetry]
name = "pmon"
version = "0.1.0"
description = ""
authors = ["laiso <laiso@lai.so>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
